version: '3'

services:
  apache:
    build:
      context: .
    container_name: apache
    ports:
      - "8888:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PHP_DISPLAY_ERRORS: 1
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 300
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DRUPAL_ADMIN_USER: ${DRUPAL_ADMIN_USER}
      DRUPAL_ADMIN_PASS: ${DRUPAL_ADMIN_PASS}
      DRUPAL_SITE_NAME: ${DRUPAL_SITE_NAME}
      DRUPAL_SITE_DOMAIN: ${DRUPAL_SITE_DOMAIN}
    volumes:
      - drupal-data:/var/www/html/dipas/htdocs/drupal/sites/default/files
    networks:
      - dipas-network

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dipas-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  drupal-data:

networks:
  dipas-network:

